### ISSUE TITLE
the drawer become black on release mode

### ISSUE THREAD

**Issue by waleedf112** [Dn-a/flutter_inner_drawer#1]
the drawer works fine on debug mode on both the emulator and a real phone, but when running on release mode or after building the apk, it disappears completely.

**this is on debug mode:**
![photo_2019-03-19_22-29-27](https://user-images.githubusercontent.com/44902066/54636029-8812e400-4a96-11e9-92bb-71e40295b550.jpg)

**this one on release mode:**
![photo_2019-03-19_22-29-30](https://user-images.githubusercontent.com/44902066/54636030-8812e400-4a96-11e9-935c-2870a115f5cf.jpg)

both of them taken without any changes in the code.

**Comment by Dn-a** [comment]
@waleedf112 happens even during the swipe?

**Comment by waleedf112** [comment]
@Dn-a yes, still haven't figured out the problem

**Comment by Dn-a** [comment]
@waleedf112 please post your flutter doctor

**Comment by waleedf112** [comment]
```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale en-US)
    • Flutter version 1.2.1 at C:\Flutter\sdk\flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Waleed\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • SM N950F • 988a16304a4e32483630 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by Dn-a** [comment]
@waleedf112 On my smartphone in release mode it works perfectly ... could you post your code?

**Comment by Dn-a** [comment]
@waleedf112 test new version 0.2.5...
Same issues solved [`03`](https://github.com/Dn-a/flutter_inner_drawer/issues/3)

**Comment by emidiao** [comment]
ciao @Dn-a, I'm having the same problem in android release mode, with both versions 0.2.6/0.2.5. In debug mode everything works fine.

![Screenshot_20190607-153618](https://user-images.githubusercontent.com/3332321/59108085-69581700-893a-11e9-8838-d2805c623fb3.png)


 
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G6030, locale it-IT)
    • Flutter version 1.5.4-hotfix.2 at /Users/emiliano/Documents/ios-dev/flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/emiliano/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.1

[✓] Connected device (1 available)
    • SM G920F • 0715f743a7702936 • android-arm64 • Android 7.0 (API 24)

**Comment by Dn-a** [comment]
Ciao @emidiao hai provato a disinstallare l'app dallo smartphone e reinstallarla in modalità release? Succede anche con Android/ios emulator?

**Comment by emidiao** [comment]
Ciao,
sto testando ora la 0.2.6. Ho provato a disinstallare prima, ma l'anomalia persiste.
Su ios non ho problemi, tutto ok con versione release su device e debug su simulatore.
Ok anche versione debug su emulatore android, il problema sembra confinato a release android su device (ho provato anche il progetto example, mi succede lo stesso).

**Comment by Dn-a** [comment]
@emidiao ho effettuato diversi test su Android 4 e Android 8 ma non ho avuto problemi. Ad oggi non sono riuscito ad identificare bene il problema...può sembrare stupida come domanda ma hai modo di effetuare gli stessi test su windows? grazie

**Comment by Dn-a** [comment]
@emidiao ho effettuato diversi test su Android, dalla versione 4.0 alla 9.0, senza riscontrare anomalie. 
Ho rilasciato l'ultima versione (ver. 0.2.7) con qualche piccola miglioria, provala e tienimi aggiornato.
