### ISSUE TITLE
about Display

### ISSUE THREAD

**Issue by 1liangzai** [Dn-a/flutter_inner_drawer#10]
When I was debugging for release, the drawer could not be displayed.

**Comment by Dn-a** [comment]
@Dn-a IOS or Android? windows or apple development environment?

**Comment by Dn-a** [comment]
@1liangzai  IOS or Android? windows or apple development environment?

**Comment by 1liangzai** [comment]
iOS&Android

**Comment by 1liangzai** [comment]
> @1liangzai IOS or Android? windows or apple development environment?

iOS&Android

**Comment by 1liangzai** [comment]
> @1liangzai IOS or Android? windows or apple development environment?

apple development environment

**Comment by 1liangzai** [comment]
I tried to run demo on Android and iOS at the same time. As a result, the drawer area was black.
1. "flutter build apk" or "flutter build ios --release"
2.Runing the iOS or Android app
3.The drawer does not display

**Comment by Dn-a** [comment]
@1liangzai occurs only in the iOS development environment

**Comment by Dn-a** [comment]
@1liangzai I did some updating. try version 0.3.0 and let me know

**Comment by 1liangzai** [comment]
@Dn-a Hi! This problem also exists in version 0.3.0.

**Comment by 1liangzai** [comment]
@Dn-a Hi! This problem also exists in version 0.3.0.
I only tested Android and iOS in the Mac development environment, and I haven't tried Windows yet.

**Comment by Dn-a** [comment]
@1liangzai have you tried version 0.5.1?

**Comment by 1liangzai** [comment]
@Dn-a I just tried,it's no problem.

**Comment by Dn-a** [comment]
@1liangzai great! Can i close the problem?

**Comment by 1liangzai** [comment]
@Dn-a Yes!Of course.I'm sorry for the late reply
