### ISSUE TITLE
Two menus left and right at same time???

### ISSUE THREAD

**Issue by yohane55** [Dn-a/flutter_inner_drawer#11]
how can we have both left and right different inner menus just like [SlidingMenu](https://github.com/jfeinstein10/SlidingMenu) so the user can swipe left and write to open different panels.

**Comment by Dn-a** [comment]
@yohane55 I'm working on it.
stay tuned

**Comment by furkankurt** [comment]
> @yohane55 I'm working on it.
> stay tuned

I'm also waiting, thank you 💯 👍 🥇

**Comment by yohane55** [comment]
@Dn-a is going to happen any time soon?

**Comment by Dn-a** [comment]
@yohane55 yes

**Comment by Dn-a** [comment]
@yohane55 @furkankurt new release 0.4.0.
check and leave feedback
