### ISSUE TITLE
Need to control open and close state of left-child and right-child  separately. 

### ISSUE THREAD

**Issue by resilientbd** [Dn-a/flutter_inner_drawer#13]
Hi, I am using 0.4.0 version. Instead of using left swipe or right swipe I want to use buttons. I used innerDrawerKey.currentState.open and innerDrawerKey.currentState.close method to open and close drawers. But the problem is I can not open or close one drawer specifically with button clicks. 
So, I am wondering if is there any way to manage the open and closed state of left-child and right-child separately.

**Comment by Dn-a** [comment]
@resilientbd you could do this
```
//for left child
_innerDrawerKey.currentState.open(                                 
        direction: InnerDrawerDirection.start
);
_innerDrawerKey.currentState.close(                                 
        direction: InnerDrawerDirection.start
);

//for Right child
_innerDrawerKey.currentState.open(                                 
        direction: InnerDrawerDirection.end
);
_innerDrawerKey.currentState.close(                                 
        direction: InnerDrawerDirection.end
);
```

**Comment by resilientbd** [comment]
Thank you very much. it worked!
