### ISSUE TITLE
leftOffset in px and disable shadow ?

### ISSUE THREAD

**Issue by NicolasCELLA** [Dn-a/flutter_inner_drawer#15]
Hello, it's possible to configure "leftOffset" in px but not in percent ?

And if it's possible to disable shadow ? 

😇

**Comment by Dn-a** [comment]
@NicolasCELLA 
 1. No 
2.set `boxshadow:[],`

**Comment by Dn-a** [comment]
@NicolasCELLA solved?

**Comment by NicolasCELLA** [comment]
Yes thank 👌

In feature I think it would be nice to be able to swipe on the "leftOffset" directly to leave it 
(like instagram or twitter)

After that, a think your drawer can be perfect 😎

![Image](https://s3.eu-west-3.amazonaws.com/pikomit-local/images/EXH6RjtSCih3x35UsFdFL5CKMA8zo21573004016026.jpg)

**Comment by Dn-a** [comment]
@NicolasCELLA what is the offset parameter?

**Comment by NicolasCELLA** [comment]
The possibility to leave the offsetLeft in sliding in left ! Presently we need to tap the scaffold to come back ! 
I think that can be nice 😇
