### ISSUE TITLE
Opening drawer by tabbing menu button

### ISSUE THREAD

**Issue by kaiserleka** [Dn-a/flutter_inner_drawer#22]
Is there a way to open this drawer by tabbing hamburger menu icon (among appbar title) instead of swiping?

**Comment by Dn-a** [comment]
@kaiserleka yes, by creating a custom button that invokes the method
```
final GlobalKey<InnerDrawerState> _innerDrawerKey = GlobalKey<InnerDrawerState>();  
_innerDrawerKey.currentState.toggle()
//OR
_innerDrawerKey.currentState.toggle()
_innerDrawerKey.currentState.close()
```

**Comment by kaiserleka** [comment]
Thanks!
I have applied these with callbacks (cause I have located InnerDrawer in a common widget to use on everypages.

Now my hamburger menu button can open the innerDrawer
