### ISSUE TITLE
Change the scaffold when an item is selected

### ISSUE THREAD

**Issue by istornz** [Dn-a/flutter_inner_drawer#24]
Hello !
First thanks for this awesome package !
I have an application which use inner_drawer like this:
- A home scaffold
- A right child, which is the main menu off my app.
When the user open the right menu and choose an item, I would like to close the menu **AND** change the main scaffold using the statefull widget corresponding in the menu.
The only problem I have, is how to change the main scaffold ?

I have an idea to create a "Router Page" assigned to the main scaffold and change the returned Widget according, is it the good philosophy concerning this package ?

Thanks for the answer :)
Have a nice day !

**Comment by istornz** [comment]
I achieved what I wanted.
Maybe it can help:
I created a Router Page which embedded a BlocBuilder Widget :)

**Comment by Dn-a** [comment]
@istornz the solutions adopted for the drawer can also be adopted for innerDrawer.  BlocBuilder is a great choice :)
