### ISSUE TITLE
Can't hide keyboard when toggling the drawer

### ISSUE THREAD

**Issue by brettpappas** [Dn-a/flutter_inner_drawer#25]
I can't get rid of the soft-keyboard when I toggle the drawer open and closed. I have tried putting a GestureDetector around the button but it is getting ignored.

```dart
class SideBarButtonOpener extends StatelessWidget {
  SideBarButtonOpener({
    Key key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        print('toggling drawer...');
        FocusScope.of(context).unfocus();
      },
      child: NavBarButton(
        icon: Icons.menu,
        color: Colors.white,
        onPressed: () {
          Provider.of<LayoutProvider>(context, listen:false).currentDrawer.currentState.toggle();
        },
      ),
    );
  }
}
```

**Comment by Dn-a** [comment]
@brettpappas could you provide more information? Thanks

**Comment by brettpappas** [comment]
I would be happy to provide more info. Can you let me know what would be helpful? Screenshots? I provided the relavant code but would be happy to include more.

**Comment by Dn-a** [comment]
@brettpappas It would be useful to understand how the keyboard is invoked, providing the code that it interacts with innerdrawer

**Comment by brettpappas** [comment]
The keyboard is simply invoked by tapping a TextField to give it focus. For instance - my main screen is a ListView with a search box at the top. If I tap inside the search field the keyboard shows up and then if I tap on my drawer icon (or swipe) to open the menu - the keyboard stays.

I normally include a GestureDetector at the top level of my app like this:
```dart
return InnerDrawer(
    key: currentDrawer,
    onTapClose: true,
    swipe: true,
    leftOffset: 0.5,
    leftScale: 1,
    rightScale: 1,
    borderRadius: 30,
    leftAnimationType: InnerDrawerAnimation.quadratic,
    tapScaffoldEnabled: false,
    colorTransition: Colors.black,
    leftChild: SideDrawer(),
    scaffold: GestureDetector(
      onTap: () {
        print('gesture detected');
        FocusScopeNode currentFocus = FocusScope.of(context);

        if (!currentFocus.hasPrimaryFocus) {
          currentFocus.unfocus();
        }
      },
      child: ContactList()
    ),
);
```

This gets ignored because the InnerDrawer widget has it's own GestureDetector that overrides mine so mine does not get called. Looks like you have an empty onTap (https://github.com/Dn-a/flutter_inner_drawer/blob/master/lib/inner_drawer.dart#L578).

I can work around part of this by adding the `unfocus` to my button onPressed event but it still has the issue with swipe events.

**Comment by Dn-a** [comment]
@brettpappas take a look here [link](https://api.flutter.dev/flutter/widgets/AndroidView/gestureRecognizers.html)
it should be the solution to your problem

**Comment by Dn-a** [comment]
@brettpappas solved?
