### ISSUE TITLE
Drawer become black in release model

### ISSUE THREAD

**Issue by huangjianke** [Dn-a/flutter_inner_drawer#3]
![image](https://user-images.githubusercontent.com/8692455/56268690-88011500-6124-11e9-9c25-a536b0eb6667.png)

**Comment by huangjianke** [comment]
flutter_inner_drawer: ^0.2.4

**Comment by Dn-a** [comment]
@huangjianke  flutter version? please post your code

**Comment by huangjianke** [comment]
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.2 18C54, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.33.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`

@Dn-a

**Comment by huangjianke** [comment]
![image](https://user-images.githubusercontent.com/8692455/56302879-43e63280-616d-11e9-828b-977949431b2a.png)

**Comment by Dn-a** [comment]
@huangjianke I tried your code in release mode but I have no problems...with animationType: static / quadratic occurs? I can't understand where the problem is. update flutter to the latest version and let me know

**Comment by huangjianke** [comment]
@Dn-a Hi, Thanks for your reply

https://github.com/huangjianke/flutter_example

this is the example project, there is no problems in Andriod but it's black in iPhone X

**Comment by Dn-a** [comment]
@huangjianke 
Unfortunately I have no way to try on iPhone X...
I made some improvements to the code, install version 0.2.5 to see if you solve. Some precautions: uninstall the app from your smartphone before reinstalling the new version in release mode.

**Comment by huangjianke** [comment]
@Dn-a 
Thanks, It's OK now
