### ISSUE TITLE
Arrow back icon when drawer open

### ISSUE THREAD

**Issue by robi2908** [Dn-a/flutter_inner_drawer#31]
how can i remove the back arrow in the app bar when i open the drawer?

**Comment by brandon8863** [comment]
Sounds like you're after not showing the back arrow when inner drawer is open. You could use the innerDrawerCallback to set a bool _isOpen variable on your view that you would use to enable or disable the leading back arrow.

The docs on AppBar give a good example of not relying on automaticallyImplyLeading and defining your own "leading" widgets on AppBar. In your case AppBar.leading would be null when the drawer is open and have the default behavior when it's closed.

Good luck!

**Comment by robi2908** [comment]
solved, perfect thank you very much!

**Comment by lalitjarwal** [comment]
The solution didnt work for me!
this is the code..
` Widget build(BuildContext context) {
    return InnerDrawer(
        colorTransitionChild: Colors.transparent,
        onTapClose: true,
        // tapScaffoldEnabled: true,
        boxShadow: [BoxShadow(color: Colors.grey)],
        //proportionalChildArea: false,
        //borderRadius: 12,
        innerDrawerCallback: (isOpened) {
          _isOpen = isOpened;
          print(_isOpen);
        },
        swipe: true,
        scale: IDOffset.horizontal(1),
        colorTransitionScaffold: Colors.transparent,
        offset: IDOffset.horizontal(0.15),
        key: key,
        rightChild: Container(
          color: Colors.white,
        ),
        scaffold: Scaffold(
          appBar: AppBar(
            leading: null,
            elevation: 1,
            title: Text('flutter.dart.lang'),
            actions: [
              IconButton(
                  icon: Icon(Icons.menu),
                  onPressed: () {
                    key.currentState.toggle();
                  })
            ],
          ),
        ));
  }`
