### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by hz111-hz112** [Dn-a/flutter_inner_drawer#32]
How can i navigate between pages using only one drawer ? Can you show very simple example ?

**Comment by hz111-hz112** [comment]
I want to go another page but it has a same drawer but only one code for drawer. In your example , for example click dahsboard and go to dashboardPage and open drawer again and click user and go userPage with using one drawer. Simple example navigation please.

**Comment by Dn-a** [comment]
hi @hz111-hz112, as soon as I have time I will give some examples.

**Comment by hz111-hz112** [comment]
Thank you so much, i am waiting
