### ISSUE TITLE
Lagging while using it inside PageView

### ISSUE THREAD

**Issue by o4x** [Dn-a/flutter_inner_drawer#34]
When I use it in the a PageView everything slows down.🤔

**Comment by Dn-a** [comment]
@o4x provide details by publishing the source code

**Comment by o4x** [comment]
Oh In fact, I was wrong.
The reason for lagging is rebuilding scaffold while closing or opening drawer. Is there a way to disable it ?

**Comment by Dn-a** [comment]
@o4x I have not experienced this combination ... I should try it

**Comment by o4x** [comment]
The problem was my code, sorry😓
