### ISSUE TITLE
innerDrawerCallback fired multiple times

### ISSUE THREAD

**Issue by dimitristaufer** [Dn-a/flutter_inner_drawer#4]
First of all, thanks for creating this amazing widget!

I guess this is not really a bug, it's simply the way you implemented the innerDrawerCallback. When using a swipe gesture to open/close the drawer, I receive multiple callbacks (false, false, true when opening and true, true, false when closing).

My issue is, that I only want one callback when the drawer is closed, so that I can safely perform one single update on the main screen.

Any chance you could change this or give me a hint on how I could implement this? Thank You.

**Comment by Dn-a** [comment]
@dimitristaufer 
thanks for your feedback!
it's a small problem that I'll fix in the next version

**Comment by dimitristaufer** [comment]
Awesome!
Any idea when we can expect your next release?

**Comment by Dn-a** [comment]
@dimitristaufer few days.

**Comment by Dn-a** [comment]
@dimitristaufer 
in version 0.2.6 it should work correctly,

**Comment by dimitristaufer** [comment]
Yes, perfect - thank you.
