### ISSUE TITLE
Toogle drawer via _innerDrawerKey.currentState.toggle()

### ISSUE THREAD

**Issue by uvlek** [Dn-a/flutter_inner_drawer#41]
I think its not a bug. But can you help me how deal with it?

When I use _innerDrawerKey.currentState.toggle() - it open/close previously right or lelt panel. But I need toggle specific side - left (When user click menu button - it must open left panel)

Thhanks!

**Comment by Dn-a** [comment]
hi @uvlek, can do it very simply like this:
```
_innerDrawerKey.currentState.open(
direction: InnerDrawerDirection.start // left
// OR
direction: InnerDrawerDirection.end // right
)
```

**Comment by uvlek** [comment]
Thank you @Dn-a !
