### ISSUE TITLE
When swipe set to true, then 'back' button on navigation bar not working

### ISSUE THREAD

**Issue by KingWu** [Dn-a/flutter_inner_drawer#5]
I have a two page, Dashboard page and slidepanel page.
Click a button in Dashboard page and then go to slidepanel page.

I set 'swipe' parameter to be true. i click 'back' button on navigation bar. it cannot back to Dashboard.

Also, i call Navigator.pop(context), which also not work.

**Comment by Dn-a** [comment]
@KingWu please post your code here.

**Comment by Dn-a** [comment]
@KingWu you solved?

**Comment by brandon8863** [comment]
I also noticed enabling swipe gets too aggressive removing history from the root navigation queue. I'll see if I can find time for a fix and PR. Thanks for the work on this!

**Comment by Dn-a** [comment]
@brandon8863 the back button does not close?

**Comment by brandon8863** [comment]
Ya beat me to a PR. Yes, commenting out the call to _ensureHistoryEntry() in _handleDragDown fixes the issue.
