### ISSUE TITLE
add null-safety support

### ISSUE THREAD

**Issue by chavesgu** [Dn-a/flutter_inner_drawer#67]
flutter stable version is `2.0.0`
package need merge to null-safety
[https://dart.dev/null-safety/migration-guide](https://dart.dev/null-safety/migration-guide)

**Comment by chavesgu** [comment]
#68

**Comment by AliHoseinpoor** [comment]
please support null safety

**Comment by Dn-a** [comment]
New version 1.0.0 which supports null safety
