### ISSUE TITLE
Make the visible scaffold clickable

### ISSUE THREAD

**Issue by Bernardomrf** [Dn-a/flutter_inner_drawer#9]
When the the Inner Drawer is open, is it possible to have the scaffold scrollable and clickable without closing the drawer? In my case, I have a map on the scaffold and the map legend on the inner drawer, and I would like to scroll the map while having the legend visible.

**Comment by Dn-a** [comment]
@Bernardomrf new release 0.4.0.
check and leave feedback

**Comment by Bernardomrf** [comment]
Thank you, it works great!
